### PR TITLE
Improvement/configure cTDP

### PR DESCRIPTION
**Pull request by DEvil0000**
#26

### CODE REVIEW

**Comment by DEvil0000** [comment]
additionally we should maybe check 0xCE bit 29 and bits 34:33.
(bit 30 for temperature target)

**Comment by DEvil0000** [comment]
are you fine with it?

**Comment by erpalma** [comment]
Sorry, I was busy with the DEF CON 26 CTF lately. I just reviewed your commits and they seems quite ok. I'm having a look at your questions now, although I think the register is right because I spent a few days looking at the (several) Intel datasheets.

**Comment by erpalma** [comment]
As you can see in the 8th gen datatasheet [vol 2](https://www.intel.com/content/dam/www/public/us/en/documents/datasheets/8th-gen-core-family-datasheet-vol-2.pdf) there is both 0x65c and 0x610 MSRs. The first is the platform one, I guess is an additional limit that the manufacturer/integrator can set, while the latter is the package power limit. We can override both just to be safe but in my T480s they are both set to 90W.

**Comment by DEvil0000** [comment]
I was reading this [vol 4](https://software.intel.com/sites/default/files/managed/22/0d/335592-sdm-vol-4.pdf) datasheet all the time

**Pull request merged**
